# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e5e1eebd7202a2173a5a98c1158c5c51efe47ff15a21925b649b3f283e116915a1c81210c9dd119ca41ec652bd7130f1fe28f68d799eb047f49b331dd9fa8f8

test:
  secret_key_base: 0f086d93be845db0ff5eaab412f9897fb907879c4db9be5a449734d1c02878b9c2f495f679ea1baea9931251b268dab1feefa2ad61455f5b741b05f7436298ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
